"""Add slug to wishlist

Revision ID: e0b595f1d733
Revises: 8a52d5f7ae7d
Create Date: 2025-12-21 14:44:40.886739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b595f1d733'
down_revision = '8a52d5f7ae7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=32), nullable=False))
        batch_op.create_index(batch_op.f('ix_wishlists_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlists_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
